<a href="https://colab.research.google.com/github/institutohumai/cursos-python/blob/master/AnalisisDeDatos/1_Indexing/ejercicio/ejercicio.ipynb"> <img src='https://colab.research.google.com/assets/colab-badge.svg' /> </a>
<div align="center"> Recordá abrir en una nueva pestaña </div>


Para este ejercicio vamos a importar un conjunto de datos con el listado de colegios públicos de Bogotá del año 2016

# Ejercicio I: base de Colegios de Bogotá.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_colegios = pd.read_csv('https://www.datos.gov.co/api/views/qijw-htwa/rows.csv?accessType=DOWNLOAD')

¿Cuáles son las columnas? ¿Cuántas filas tiene?

In [15]:
#¿Cuáles son las columnas?
print('Las columnas son: \n', df_colegios.columns)

Las columnas son:
 Index(['año', 'secretaria', 'nombreestablecimiento', 'zona', 'direccion',
       'telefono', 'nombre_Rector', 'tipo_Establecimiento', 'etnias', 'sector',
       'genero', 'niveles', 'jornadas', 'caracter', 'especialidad', 'grados',
       'modelos_Educativos', 'capacidades_Excepcionales', 'discapacidades',
       'idiomas', 'numero_de_Sedes', 'estado', 'prestador_de_Servicio',
       'propiedad_Planta_Fisica', 'resguardo', 'matricula_Contratada',
       'calendario', 'internado', 'estrato_Socio_Economico',
       'correo_Electronico'],
      dtype='object')

In [16]:
#¿Cuántas filas tiene?
#df_colegios.shape
print('Tiene ',df_colegios.shape[0],' filas')

Tiene  2404  filas

Seleccionen los colegios donde la propiedad de la planta física sea de una persona natural o comunidad religiosa.

In [25]:
#df_colegios['propiedad_Planta_Fisica']
df_colegios.query('propiedad_Planta_Fisica == "PERSONA NATURAL" | propiedad_Planta_Fisica =="COMUNIDAD RELIGIOSA"')

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,...,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
0,2016,BOGOTA,INST DE BTO TEC COMERCIAL PITAGORAS ...,URBANA,KR 5 11 67,5665677 / 3429092,YOLANDA ARIAS CRUZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pitagoras@pitagoras.edu.co
1,2016,BOGOTA,GIMNASIO INFANTIL FEDERICO FROEBEL,URBANA,CL 32 SUR 52 A 54,7100349,SANDRA MILENA MENDEZ,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,gimfedebel@hotmail.com
2,2016,BOGOTA,GIMNASIO INFANTIL LOS NIÑOS DEL MAÑANA,URBANA,CL 134 D 47 27,6010350,CLAUDIA BOCACHICA SAENZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,claudialindenibocachica@hotmail.com
4,2016,BOGOTA,COL SAN JUAN VIANETH ...,URBANA,KR 2 C 3 18 SUR,2804738 -- 4714934,GLORIA ESPERANZA CHUQUIN LAISECA,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,colegiosanjuanviateh@hotmail.com -- colegiosan...
5,2016,BOGOTA,COL SAN PATRICIO ...,URBANA,KR 80 137 02,6838640 -- 6815357,PAULINA ENCINALES DE SANJINES,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,correo@colegiodesanpatricio.edu.co
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399,2016,BOGOTA,COLEGIO SAN JOSE DE CALASANZ,URBANA,CL 129 88 B 35,6854492 -- 6854495 -- 6803549,GLADIS CUÉLLAR IBAÑEZ,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,COMUNIDAD RELIGIOSA,COMUNIDAD RELIGIOSA,NO APLICA,NO,A,NaN,NaN,csjcsuba@yahoo.es
2400,2016,BOGOTA,COL NUEVO REINO DE TURINGIA,URBANA,KR 103 B 152 C 34,6830915,RUTH CECILIA CORREA FAJARDO,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,jibnuevoreinodeturingia@hotmail.com - ruth_cec...
2401,2016,BOGOTA,LIC INF GOOFY ...,URBANA,CL 65 F SUR 78 C 32,7761739 / 7762538 / 7753157 /8045802,SANDRA PATRICIA SANTAMARIA OVALLE,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,pattysantaco@yahoo.com directoragoofy@gmail....
2402,2016,BOGOTA,LIC APRENDO CON MIS AMIGOS ...,URBANA,CR. 94 NO.29-30,2671099,YANNETH CONSUELO BOLIVAR GAITAN,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,NaN
2403,2016,BOGOTA,JARD INF EL ROSAL DE MI INFANCIA ...,URBANA,TR. 56A NO.45-18 SUR,7242172,ADALGIZA LADINO,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,adalgizaladino@hotmail.com ...

¿Hay alguno de estos colegios que sea para capacidades excepcionales?

In [48]:
df_colegios.query?

Signature: df_colegios.query(expr: 'str', inplace: 'bool' = False, **kwargs)
Docstring:
Query the columns of a DataFrame with a boolean expression.

Parameters
----------
expr : str
    The query string to evaluate.

    You can refer to variables
    in the environment by prefixing them with an '@' character like
    ``@a + b``.

    You can refer to column names that are not valid Python variable names
    by surrounding them in backticks. Thus, column names containing spaces
    or punctuations (besides underscores) or starting with digits must be
    surrounded by backticks. (For example, a column named "Area (cm^2)" would
    be referenced as ```Area (cm^2)```). Column names which are Python keywords
    (like "list", "for", "import", etc) cannot be used.

    For example, if one of your columns is called ``a a`` and you want
    to sum it with ``b``, your query should be ```a a` + b``.

    .. versionadded:: 0.25.0
        Backtick quoting introduced.

    .. versionadded:: 1.0.0
        Expanding functionality of backtick quoting for more than only spaces.

inplace : bool
    Whether the query should modify the data in place or return
    a modified copy.
**kwargs
    See the documentation for :func:`eval` for complete details
    on the keyword arguments accepted by :meth:`DataFrame.query`.

Returns
-------
DataFrame or None
    DataFrame resulting from the provided query expression or
    None if ``inplace=True``.

See Also
--------
eval : Evaluate a string describing operations on
    DataFrame columns.
DataFrame.eval : Evaluate a string describing operations on
    DataFrame columns.

Notes
-----
The result of the evaluation of this expression is first passed to
:attr:`DataFrame.loc` and if that fails because of a
multidimensional key (e.g., a DataFrame) then the result will be passed
to :meth:`DataFrame.__getitem__`.

This method uses the top-level :func:`eval` function to
evaluate the passed query.

The :meth:`~pandas.DataFrame.query` method uses a slightly
modified Python syntax by default. For example, the ``&`` and ``|``
(bitwise) operators have the precedence of their boolean cousins,
:keyword:`and` and :keyword:`or`. This *is* syntactically valid Python,
however the semantics are different.

You can change the semantics of the expression by passing the keyword
argument ``parser='python'``. This enforces the same semantics as
evaluation in Python space. Likewise, you can pass ``engine='python'``
to evaluate an expression using Python itself as a backend. This is not
recommended as it is inefficient compared to using ``numexpr`` as the
engine.

The :attr:`DataFrame.index` and
:attr:`DataFrame.columns` attributes of the
:class:`~pandas.DataFrame` instance are placed in the query namespace
by default, which allows you to treat both the index and columns of the
frame as a column in the frame.
The identifier ``index`` is used for the frame index; you can also
use the name of the index to identify it in a query. Please note that
Python keywords may not be used as identifiers.

For further details and examples see the ``query`` documentation in
:ref:`indexing <indexing.query>`.

*Backtick quoted variables*

Backtick quoted variables are parsed as literal Python code and
are converted internally to a Python valid identifier.
This can lead to the following problems.

During parsing a number of disallowed characters inside the backtick
quoted string are replaced by strings that are allowed as a Python identifier.
These characters include all operators in Python, the space character, the
question mark, the exclamation mark, the dollar sign, and the euro sign.
For other characters that fall outside the ASCII range (U+0001..U+007F)
and those that are not further specified in PEP 3131,
the query parser will raise an error.
This excludes whitespace different than the space character,
but also the hashtag (as it is used for comments) and the backtick
itself (backtick can also not be escaped).

In a special case, quotes that make a pair around a backtick can
confuse the parser.
For example, ```it's` > `that's``` will raise an error,
as it forms a quoted string (``'s > `that'``) with a backtick inside.

See also the Python documentation about lexical analysis
(https://docs.python.org/3/reference/lexical_analysis.html)
in combination with the source code in :mod:`pandas.core.computation.parsing`.

Examples
--------
>>> df = pd.DataFrame({'A': range(1, 6),
...                    'B': range(10, 0, -2),
...                    'C C': range(10, 5, -1)})
>>> df
   A   B  C C
0  1  10   10
1  2   8    9
2  3   6    8
3  4   4    7
4  5   2    6
>>> df.query('A > B')
   A  B  C C
4  5  2    6

The previous expression is equivalent to

>>> df[df.A > df.B]
   A  B  C C
4  5  2    6

For columns with spaces in their name, you can use backtick quoting.

>>> df.query('B == `C C`')
   A   B  C C
0  1  10   10

The previous expression is equivalent to

>>> df[df.B == df['C C']]
   A   B  C C
0  1  10   10
File:      c:\users\loren\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages\pandas\core\frame.py
Type:      method

In [53]:
#df_colegios['capacidades_Excepcionales']
df_perN_comR = df_colegios.query('propiedad_Planta_Fisica == "PERSONA NATURAL" | propiedad_Planta_Fisica =="COMUNIDAD RELIGIOSA"')
df_perN_comR.query('not capacidades_Excepcionales.isnull()')  #ambas formas funcionan
df_perN_comR[df_perN_comR["capacidades_Excepcionales"].notna()]

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,...,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
263,2016,BOGOTA,COL CAMPESTRE MAXIMINO POITIERS ...,URBANA,KR 92 148 51,6835013 / 6841539 ...,KILIAN ALEXANDER ARENAS SANABRIA,INSTITUCION EDUCATIVA,AMORÚA,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,kilanarenas@hotmail.com ...
507,2016,BOGOTA,LIC VAL (VIDA-AMOR-LUZ) ...,URBANA,CL 71 C 51 31,2251109 -- 2401331 -- 2502167,LUZ ESPERANZA MORALES SARMIENTO,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,liceo.vida.amor.luz.2@gmail.com
1012,2016,BOGOTA,LIC ECOLOGICO DEL NORTE ...,URBANA,CR. 98A NO.156D-26,6822591 / 6839957 ...,JULIA ALICIA PELAEZ CASTILLO,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,semillasverdes@hotmail.com ...
1367,2016,BOGOTA,GIMNASIO CAMPESTRE STEPHEN HAWKING,URBANA,KR 68 173 A 50,6718575 -- 3005581260,DORA ASTRID PARDO AVILA,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,SI,A,NaN,NaN,gcstephenhawking@gmail.com
1964,2016,BOGOTA,COL JONATHAN SWIFT ...,URBANA,KR 90 163 30,6818191,DIANA J. MARQUEZ S.,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,COLEGIOJONTHANSWIFT@YAHOO.COM.CO ...
2282,2016,BOGOTA,COL CALATRAVA,URBANA,KR 80 156 95,6847860,CONSUELO VALDERRAMA MORALES,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,B,NaN,NaN,info@colegiocalatrava.edu.co - rectoria@colegi...
2341,2016,BOGOTA,INST DE PEDAG AUTOACTIVA DE GRUPOS (IPAG) ...,URBANA,KR 8 C 183 32,6711029 -- 6701198,CARMEN TULIA CORDOBA ACOSTA,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,colegioipag@gmail.com

¿Cuáles son los colegios que ofrecen todos los niveles educativos? ¿Qué idiomas ofrecen?

In [80]:
niveles_completo = 'PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIMARIA,PRIMERA INFANCIA'
df_colegios.query(f'niveles == "{niveles_completo}"') #andan las 2 formas
#df_niveles = df_colegios[df_colegios['niveles'] == niveles_completo]

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,...,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
5,2016,BOGOTA,COL SAN PATRICIO ...,URBANA,KR 80 137 02,6838640 -- 6815357,PAULINA ENCINALES DE SANJINES,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,correo@colegiodesanpatricio.edu.co
1031,2016,BOGOTA,INSTITUTO JUAN PABLO II,URBANA,DG 71 C BIS SUR 77 H 17,7757668,AMPARO BENAVIDES ALBARRACIN,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,institujuan2@hotmail.com
1065,2016,BOGOTA,COLEGIO TOMAS CARRASQUILLA (IED),URBANA,CL 74 A 63 04,6603161 -- 2407959 -- 2400101,ROSA ADELINA RODRIGUEZ RODRIGUEZ,INSTITUCION EDUCATIVA,NaN,NaN,...,2,NaN,OFICIAL,OFICIAL,NO APLICA,NO,A,NaN,NaN,colditomascarrasqu12@redp.edu.co
1450,2016,BOGOTA,COLOMBO BRITANICO - BILINGÜE INTERNACIONAL,URBANA,IND AEROPUERTO GUAYMARAL COSTADO SUR OCCIDENTAL,6683999,WALTER ABONDANO MIKAN,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,info@gcb.edu.co -- ruby.gonzalez@gcb.edu.co
2236,2016,BOGOTA,COLEGIO NUEVO HORIZONTE (IED),"RURAL,URBANA",KR 5 B 189 B 30,6793861 - 6796685,HAROLD RODRIGO MURILLO TOVAR,INSTITUCION EDUCATIVA,NaN,NaN,...,4,NaN,OFICIAL,OFICIAL,NO APLICA,NO,A,NaN,NaN,cednvohorizonte1@redp.edu.co

# Ejercicio II: PyEPH

### PyEPH

La librería Pyeph tiene como objetivo facilitar el procesamiento en Python de las Encuesta Permanente de Hogares (eph) publicadas por INDEC de forma periódica. Está pensada como un espacio donde se nuclean y centralizan los cálculos vinculados a las mismas para posteriormente ser utilizadas en investigaciones, artículos, publicaciones, etc. Es una librería que hace principal hincapié en la transparencia metodológica utilizando licencias de código abierto y que promueve la colaboración de las comunidades de cientístas de datos, sociales, investigadorxs, desarrolladorxs, periodistas y demás curiosxs.

https://github.com/institutohumai/pyeph

Para entender qué representan las columnas ver documentación:


https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_diseno_reg_t414.pdf

In [ ]:
# Instalamos la librería.

!pip install pyeph

In [ ]:
import pyeph

In [ ]:
# Ejemplo: traemos el 2do trimestre del 2021
eph = pyeph.get(data="eph", year=2021, period=2, base_type='individual') # EPH individual

Obtenido con exito: base_individual_2021T2.zip

In [ ]:
eph.columns

Index(['CODUSU', 'ANO4', 'TRIMESTRE', 'NRO_HOGAR', 'COMPONENTE', 'H15',
       'REGION', 'MAS_500', 'AGLOMERADO', 'PONDERA',
       ...
       'PDECIFR', 'ADECIFR', 'IPCF', 'DECCFR', 'IDECCFR', 'RDECCFR', 'GDECCFR',
       'PDECCFR', 'ADECCFR', 'PONDIH'],
      dtype='object', length=177)

**Primer paso.** Crear una variable llamada eph_2 que contenga las siguientes columnas para realizar el siguiente análisis:

Edad (**CH_06**), Sexo (**CH_04**), Ingreso de la ocupación principal (**P21**), Categoría ocupacional (**CAT_OCUP**), Condición de actividad (ESTADO), Ponderación (**PONDERA**)

Referencias:

Sexo:
*   01 = Varón 
*   02 = Mujer

Categoría ocupacional (para ocupados y desocupados con
ocupación anterior):
*   1 = Patrón
*   2 = Cuenta propia
*   3 = Obrero o empleado
*   4 = Trabajador familiar sin remuneración
*   9 = Ns/Nr

Estado - Condición de actividad:
*   0 = Entrevista individual no realizada
*   1 = Ocupado 
*   2 = Descoupado
*   3 = Inactivo
*   4 = menor de 10 años

In [ ]:
#Filtramos por columnas
eph_2=eph[["CH06", "CH04", "P21", "CAT_OCUP", "ESTADO", "PONDERA"]]

In [ ]:
#Renombramos columnas
eph_2.columns=["edad", "sexo", "ingreso", "cat_ocup", "estado", "pondera"]

La columna **pondera** representa un estimado poblacional de las personas que representa cada fila. Por lo tanto, para cada cálculo es necesario operar con esa columna. Por ejemplo, la fila 0 representa a 214 personas de 58 años de sexo masculino, que tienen $50.000 de ingreso de la ocupación principal, su categoría es cuentapropista y pertenecen al segmento de ocupados.

In [ ]:
eph_2.head()

   edad  sexo  ingreso  cat_ocup  estado  pondera
0    58     1    50000         2       1      214
1    24     1        0         3       2      214
2    51     2        0         4       1      192
3    27     1     4000         2       1      192
4    18     1        0         0       3      192

a) Traer un dataframe que filtre solo a las personas que tengan 21 años o menos.

b) Traer un dataframe que filtre a las personas desocupadas de más de 40 años.

c) ¿Cuántas mujeres hay en la base de datos? ¿Y hombres?

d) ¿Cuál era la tasa de desocupación en el período seleccionado para las mujeres? ¿Era más alta o más baja que la de los hombres? (Extra: pensar el resultado usando una función)

Nota: la tasa se calcula como Desocupados / (Ocupados + Desocupados)